### ISSUE TITLE
Resizing

### ISSUE THREAD

**Issue by fancyFranci** [joomla-projects/gsoc19_page-builder#16]
### ToDo
- [x] resizing persists after saving
- [x] the "add column" button is always last
- [x] resizing an element moves its successors to the right (and next line) they don't "jump" down
- [ ] there is no gap between elements (I guess, it's not possible to generate this "gap" in the frontend...if it's possible, then the gap is ok)
- [x] Frontend template renders the elements correctly
- [ ] Drag & Drop ordering of elements
